# CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_SLEEP=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_HID=y


# Enable underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
